// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJf05Xjsc1IFS0AKGX1ANpKV1gNGD8TkE',
    appId: '1:506788540060:web:775b920de38e4e6507c759',
    messagingSenderId: '506788540060',
    projectId: 'driveiq-cc5f5',
    authDomain: 'driveiq-cc5f5.firebaseapp.com',
    databaseURL: 'https://driveiq-cc5f5-default-rtdb.firebaseio.com',
    storageBucket: 'driveiq-cc5f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwBRmgYadB-Qq24FRQlzOFCpCHYVEsGzA',
    appId: '1:506788540060:android:a0a74a19804df59307c759',
    messagingSenderId: '506788540060',
    projectId: 'driveiq-cc5f5',
    databaseURL: 'https://driveiq-cc5f5-default-rtdb.firebaseio.com',
    storageBucket: 'driveiq-cc5f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJb1mDwCicke5rHEhZ1CiRqNT9riLikCY',
    appId: '1:506788540060:ios:242a7a756c51a07907c759',
    messagingSenderId: '506788540060',
    projectId: 'driveiq-cc5f5',
    databaseURL: 'https://driveiq-cc5f5-default-rtdb.firebaseio.com',
    storageBucket: 'driveiq-cc5f5.firebasestorage.app',
    iosBundleId: 'com.example.airQuality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJb1mDwCicke5rHEhZ1CiRqNT9riLikCY',
    appId: '1:506788540060:ios:242a7a756c51a07907c759',
    messagingSenderId: '506788540060',
    projectId: 'driveiq-cc5f5',
    databaseURL: 'https://driveiq-cc5f5-default-rtdb.firebaseio.com',
    storageBucket: 'driveiq-cc5f5.firebasestorage.app',
    iosBundleId: 'com.example.airQuality',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJf05Xjsc1IFS0AKGX1ANpKV1gNGD8TkE',
    appId: '1:506788540060:web:cae267a4cd01929307c759',
    messagingSenderId: '506788540060',
    projectId: 'driveiq-cc5f5',
    authDomain: 'driveiq-cc5f5.firebaseapp.com',
    databaseURL: 'https://driveiq-cc5f5-default-rtdb.firebaseio.com',
    storageBucket: 'driveiq-cc5f5.firebasestorage.app',
  );

}